package main
/*

	Problem:

	Each new term in the Fibonacci sequence is generated by adding the previous
	two terms. By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not 
	exceed four million, find the sum of the even-valued terms.

*/

const LIMIT int = 4000000

func main() {
	sum := 0
	ii := 1
	for i := 2; ii < LIMIT; i += ii {
		if i % 2 == 0 {
			sum += i
		}
		t := i
		i = ii
		ii = t
	}
	println("The answer is: ", sum)
}

